### PR TITLE
Fix unsafe use of grep - Closes #211

### LINKED ISSUE #211: Unsafe use of grep in lisk.sh
If the pm2 configuration file somehow contains "name" (as might happen on Jenkins if you're building a branch called XYZ-something-name-foo-bar for instance) `PM2_APP` will not be set properly and `lisk.sh` will fail in unexpected ways.

Ref.: https://github.com/LiskHQ/lisk-build/blob/development/scripts/lisk.sh#L341 #

### PR DESCRIPTION
**Pull request by ghost**
Use jq to parse json instead of using grep.

Closes #211

### CODE REVIEW

**Comment by Isabello** [comment]
JQ is not present in 0.10.0 branch.

**Review by Isabello — DISMISSED** [review]
Please use JQ for all greps against config files.

File: scripts/lisk.sh [hunk 1]
```diff
@@ -278,7 +275,7 @@ pm2_cleanup() {
 }
 
 check_status() {
-	PM2_PID="$(pm2 describe "$PM2_APP" | grep "pid path" | cut -d' ' -f14)" >> "$SH_LOG_FILE" 2>&1> /dev/null
+	PM2_PID="$( pm2 jlist |jq ".[] | select(.name == \"$PM2_APP\").pm2_env.pm_pid_path" )"
```
Comment (Isabello) [inline scripts/lisk.sh:278]: this is cool!

File: scripts/lisk.sh [hunk 2]
```diff
@@ -338,8 +335,8 @@ parse_flag() {
 			p)
 				if [ -f "$OPTARG" ]; then
 					PM2_CONFIG="$OPTARG"
-					PM2_APP="$(grep "name" "$PM2_CONFIG" | cut -d'"' -f4)"
-					LISK_CONFIG="$(grep ".json" "$PM2_CONFIG" | cut -d'"' -f4 | cut -d' ' -f2)" >> /dev/null
+					PM2_APP="$( jq .apps[0].name -r "$PM2_CONFIG" )"
+					LISK_CONFIG="$( jq .apps[0].args -r "$PM2_CONFIG" |cut -d' ' -f2 )"
```
Comment (Isabello) [inline scripts/lisk.sh:339]: is there no way to remove the cut requirement here?

**Review by Isabello — APPROVED** [review]
